name: Tests

on: [push, pull_request]

jobs:
  tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        toolchain:
          - stable
          - beta
          - nightly
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get latest ${{ matrix.toolchain }} Rust
        run: rustup toolchain install stable --profile minimal
      - name: Check out source
        uses: actions/checkout@v2
      - name: Run tests
        run: cargo test --all
